const Web3 = require('web3');
const web3 = new Web3('http://localhost:8545'); // Change to your Ethereum node URL

const contractABI = [ /* ABI generated by compiling Solidity contract */ ];
const contractAddress = '0xYourContractAddress';
const supplyChainContract = new web3.eth.Contract(contractABI, contractAddress);

async function addProduct(name, origin, fromAddress) {
    await supplyChainContract.methods.addProduct(name, origin).send({ from: fromAddress });
    console.log('Product added successfully');
}

async function verifyProduct(id, fromAddress) {
    await supplyChainContract.methods.verifyProduct(id).send({ from: fromAddress });
    console.log('Product verified successfully');
}

async function getProduct(id) {
    const product = await supplyChainContract.methods.getProduct(id).call();
    console.log(product);
}
